apiVersion: v1
kind: Service
metadata:
  name: tensorflow-api-service
spec:
  type: NodePort
  selector:
    app: tensorflow-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
